FORMAT: 1A
HOST: http://lukitomo.com/

# Kareem 

Polls is a simple API allowing consumers to view polls and vote in them.

## Error Messages [/api/v2/config/error-messages]

### Get List of Error Messages [GET]

+ Response 200 (application/json)

        {
            "data": {
                "4001": "Mohon periksa kembali koneksi internet anda.",
                "Something went wrong during native playback": "Terjadi kesalahan saat memuat video. Silakan coba beberapa saat lagi.",
                "3100": "Mohon maaf device yang Anda gunakan tidak compatible dengan layanan kami.",
                "3101": "Mohon maaf device yang Anda gunakan tidak compatible dengan layanan kami.",
                "3102": "Mohon maaf device yang Anda gunakan tidak compatible dengan layanan kami.",
                "3103": "Mohon maaf device yang Anda gunakan tidak compatible dengan layanan kami.",
                "3104": "Mohon maaf device yang Anda gunakan tidak compatible dengan layanan kami.",
                "3105": "Mohon maaf device yang Anda gunakan tidak compatible dengan layanan kami.",
                "3106": "Mohon maaf device yang Anda gunakan tidak compatible dengan layanan kami.",
                "3107": "Mohon maaf device yang Anda gunakan tidak compatible dengan layanan kami.",
                "3108": "Mohon maaf device yang Anda gunakan tidak compatible dengan layanan kami.",
                "3109": "Mohon maaf device yang Anda gunakan tidak compatible dengan layanan kami.",
                "3110": "Mohon maaf device yang Anda gunakan tidak compatible dengan layanan kami.",
                "3111": "Mohon maaf device yang Anda gunakan tidak compatible dengan layanan kami.",
                "3112": "Mohon maaf device yang Anda gunakan tidak compatible dengan layanan kami.",
                "4006": "Tayangan hanya tersedia di Indonesia."
            }
        }

## Questions Collection [/questions]

### List All Questions [GET]

+ Response 200 (application/json)

        { 
            "data": [
                {
                    "id": 1,
                    "type": "config",
                    "attributes": [
                        {
                            "choice": "Swift",
                            "votes": 2048
                        }, {
                            "choice": "Python",
                            "votes": 1024
                        }, {
                            "choice": "Objective-C",
                            "votes": 512
                        }, {
                            "choice": "Ruby",
                            "votes": 256
                        }
                    ]
                }
            ]
        }

### Create a New Question [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
            "question": "Favourite programming language?",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }